### ISSUE TITLE
Baseline style guide

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#10]
Get the uncontroversial basics in at the beginning. As discussed at last week's meeting.

cc @ubsan @solson @joshtriplett

**Comment by ubsan** [comment]
I put one [here](https://github.com/ubsan/style/blob/master/guide.md)

**Comment by nrc** [comment]
Thanks @ubsan !

I think we need to separate out things that Rustfmt can change from things it can't. We could either have separate sections, or we could use icons or something to distinguish them.

I would remove any use of 'prefer' for now - we'll need to decide on hard character limits for when to use one vs the other. (Alternatively, you could leave in the 'prefer' bit and add a note that the Rustfmt spec is TODO).

E.g., in function definitions, I'd prefer to state precisely what is important/decided, rather than just having an example (e.g., that in `arg: Type`, there should be a single space after the `:` and no space before it).

@ubsan, should we send PRs to https://github.com/ubsan/style for smaller changes?

**Comment by joshtriplett** [comment]
:+1: to the current state of the baseline style guide.

We may end up revising the guidelines for modules and `#[path]` annotations later, but the current advice on that in the proposed baseline style guide seems fine.

**Comment by steveklabnik** [comment]
:+1: to the current guidlines, I like it.

**Comment by nrc** [comment]
+1 from me - my changes are all merged in.

**Comment by japaric** [comment]
:+1: from me, too.

**Comment by ubsan** [comment]
Fixed in #27
