### ISSUE TITLE
RFC: Prefer Guard Clause when you can assert data rather than having Nested Conditionals

### ISSUE THREAD

**Issue by danielpclark** [rust-lang-nursery/fmt-rfcs#100]
# Guard Clause

I'm taking my inspiration from Ruby for this one.

> Avoid use of nested conditionals for flow of control.  Prefer a guard clause when you can assert invalid data. A guard clause is a conditional statement at the top of a function that bails out as soon as it can. - [Ruby Style Guide @ No Nested Conditionals](https://github.com/bbatsov/ruby-style-guide#no-nested-conditionals)

First I'll provide three examples of the wrong way to do it.  These are overly nested and trying to follow the paths or guess with else belongs to what can be confusing at a glance. _These examples are a simple file config parse_

### Wrong (A)
```rust
fn read_config1() -> Result<Config, Error> {
  let file = File::open("program.cfg");
  if let Ok(f) = file {
    let mut buf_reader = BufReader::new(f);
    let mut contents = String::new();

    if buf_reader.read_to_string(&mut contents).is_ok() {
      let mut data: Vec<u8> = vec![];

      for item in contents.
          split("\n").
          map(|s| s.to_string()).
          filter(|s| !s.is_empty()).
          collect::<Vec<String>>() {

        let num = item.parse::<u8>();

        if let Ok(conf) = num {
          data.push(conf);
        } else {
          return Err(Error::ConfigParseFail);
        }
      }

      Ok( Config { data: data } )
    } else {
      Err(Error::ConfigLoadFail)
    }
  } else {
    Err(Error::ConfigLoadFail)
  }
}
```
### Wrong (B)
```rust
fn read_config2() -> Result<Config, Error> {
  let file = File::open("program.cfg");
  match file {
    Ok(f) => {
      let mut buf_reader = BufReader::new(f);
      let mut contents = String::new();

      match buf_reader.read_to_string(&mut contents) {
        Ok(_) => {
          let mut data: Vec<u8> = vec![];

          for item in contents.
              split("\n").
              map(|s| s.to_string()).
              filter(|s| !s.is_empty()).
              collect::<Vec<String>>() {

            let num = item.parse::<u8>();

            match num {
              Ok(conf) => data.push(conf),
              _ => { return Err(Error::ConfigParseFail); },
            }
          }

          Ok( Config { data: data } )
        },
        _ => { Err(Error::ConfigLoadFail) }
      }
    },
    _ => { Err(Error::ConfigLoadFail) }
  }
}
```
### Wrong (C)
```rust
fn read_config3() -> Result<Config, Error> {
  let file = File::open("program.cfg");

  if let Ok(f) = file {
    let mut buf_reader = BufReader::new(f);
    let mut contents = String::new();

    if buf_reader.read_to_string(&mut contents).is_ok() {
      let mut data: Vec<u8> = vec![];

      for item in contents.
          split("\n").
          map(|s| s.to_string()).
          filter(|s| !s.is_empty()).
          collect::<Vec<String>>() {

        let num = item.parse::<u8>();

        if let Ok(conf) = num {
          data.push(conf);
        } else {
          return Err(Error::ConfigParseFail);
        }
      }

      return Ok( Config { data: data } );
    }
  }

  Err(Error::ConfigLoadFail)
}
```

And here is the correct usage of a **Guard Clause** which allows us to avoid deeply nested logic.

### Correct
```rust
fn read_config4() -> Result<Config, Error> {
  let file = File::open("program.cfg");

  // Correct use of Guard Clause
  if file.is_err() { return Err(Error::ConfigLoadFail); }
  
  let f = file.unwrap();

  let mut buf_reader = BufReader::new(f);
  let mut contents = String::new();

  // Correct use of Guard Clause
  if buf_reader.read_to_string(&mut contents).is_err() {
    return Err(Error::ConfigLoadFail);
  }
  
  let mut data: Vec<u8> = vec![];

  for item in contents.
      split("\n").
      map(|s| s.to_string()).
      filter(|s| !s.is_empty()).
      collect::<Vec<String>>() {

    let num = item.parse::<u8>();

    match num {
      Ok(conf) => data.push(conf),
      Err(_) => { return Err(Error::ConfigParseFail); }
    }
  }

  Ok( Config { data: data } )
}
```

_If you'd like to test the examples above I have a working gist here: [danielpclark/guard_clause_rfc.rs](https://gist.github.com/danielpclark/b6f290c7addaed13883432c529c2066b) … you just need to create the config file with the contents of `"1\n2\n3\n"` ._

Having your code implemented with guard clauses adds a huge benefit for code clarity and avoids having your conditionals carry your code too far and deep to the right.

I have one pet peeve with the correct sample.  I want to write Rust without having to use `unwrap()` anywhere.  Currently

```rust
if file.is_err() { return Err(Error::ConfigLoadFail); }
let Ok(f) = file; // instead of unwrap()
```

does not work as Rust hasn't been made able to detect that the error path has already been accounted for as it says:

```
error[E0005]: refutable pattern in local binding: `Err(_)` not covered
   --> src/lib.rs:166:7
    |
166 |   let Ok(f) = file;
    |       ^^^^^ pattern `Err(_)` not covered

error: aborting due to previous error
```

which is quite sad for me to see.  Rust's pattern matching ability is one of the most beautiful features of the language and I'd like to see this ability to recognize usage of a Guard Clause added to the language to permit this pattern matching assignment.  But that's not what this RFC is about [(the one nit-pick)](https://github.com/rust-lang/rust/issues/45978), this RFC is about getting approved this preferred way to implement code in Rust as a general standard & style guide preference.

The guard clause doesn't have to be strictly for an `Error` alternate return type.  I believe it can apply for any time when there are two conditional paths and one of those paths is nothing but a return type.

**Comment by nrc** [comment]
The formatting RFCs are purely about formatting, whereas this is more of a style issue (we could never implement this using rustfmt). You might consider adding this as an idiom to https://github.com/rust-unofficial/patterns/tree/master/idioms.

FWIW, I agree with the advice here.

I think that if you are doing this with a `Result` (or `Option`) rather than a `bool`, then you should assign the inner value into a new variable, rather than using an `if ... .is_err()` and `unwrap`. E.g.,

```
fn foo(var: Result<A, B>) -> Result<C, D> {
    let var = var?;
}

// or
fn foo(var: Result<A, B>) {
    let var = match var {
        Ok(var) => var,
        Err(_) => return,
    };
}

```
