### ISSUE TITLE
Use tabs

### ISSUE THREAD

**Issue by dikti** [rust-lang-nursery/fmt-rfcs#106]
I know, I'll become unpopular by writing this, but still tabs are better. 
* Let everyone decide how much indent they want, by defining their tab width in the editor. 
* Save file size.
* Seperate data and presentation.
* Have one specific character solely for indentation, tabs are meant for this.
* Use less keypresses when navigation the cursor.
* ...

**Comment by steveklabnik** [comment]
This was already debated extensively, including all of these details. Sorry, you're too late!

**Comment by dikti** [comment]
Hah, somehow I knew. Just couldn't find it... Sorry then 🤐

**Comment by perlun** [comment]
@dikti, for reference - see #1.
