### ISSUE TITLE
Derive order.

### ISSUE THREAD

**Issue by voider1** [rust-lang-nursery/fmt-rfcs#112]
I was thinking about the Derive order, and I came up with the following:

- Firstly traits from the standard library
- Secondly traits from external Crates
- As last in the order traits from the user
- They all need to be alphabetically orderd

Example:
```rust
#[derive(Debug, Default, Display, Deserialize, Serialize, Bar, Baz, Foo)]
```

**Comment by nrc** [comment]
We can't syntactially tell custom derive from built-in derive and we can't re-order custom derives since the ordering could be significant, so we basically, we can't re-order derives.
