### ISSUE TITLE
Should `|`ed match arms be indented?

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#115]
For consistency with other binops?

E.g.,

```
Foo
    | Bar
    | Baz
```

rather than

```
Foo
| Bar
| Baz
```

I don't recall discussing this, but maybe we did.

I think we'd just have to always use `{` in the match arm and put it on a newline to make things stand out.

From https://github.com/rust-lang-nursery/rustfmt/issues/2333#issuecomment-355499476

**Comment by joshtriplett** [comment]
I thought that we did and decided on the latter. Personally, I prefer the latter over the former; I think `| ` provides enough visual distinction of continuation lines.
