### ISSUE TITLE
Immediately Invoked Closures look funny

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/fmt-rfcs#116]
Should this be fixed, or just left to feel weird? 

I wrote:

```rust

        let base_url = (|| {

            // stuff

            Ok((|| {
                // stuff
                Some(value.to_string())
            })().ok_or("")?)
        })().unwrap_or_else(|_: Box<::std::error::Error>| String::from(""));

```

formats as:

```rust

        let base_url = (|| {

            // stuff

            Ok((|| {
                // stuff
                Some(value.to_string())
            })()
                .ok_or("")?)
        })()
            .unwrap_or_else(|_: Box<::std::error::Error>| String::from(""));

```

yes, i really want `catch` to be stable.

**Comment by joshtriplett** [comment]
On the one hand, `})().foo()` seems fine. On the other hand, stacking a `?` on top of that and then sticking *that* into another function...at some point we're stacking too much. I think we could do better here, but there's a limit.

**Comment by steveklabnik** [comment]
>  I think we could do better here, but there's a limit.

I fully agree, and will not be terribly sad if we decide that this is just something we don't handle, but wanted to raise it anyway.

(My goal with this code was, "I have a mix of stuff using Option and Result, and if *anything* fails, give me an empty string, incidentally)

**Comment by nrc** [comment]
I think this is a bug in rustfmt: when we have a chain we put the second item of the chain on the same line as the first if the first is less than the indent wide to prevent orphans such as this. I think that should apply for punctuation as well as idents.

I'll open an issue on Rustfmt.
