### ISSUE TITLE
Is an initial `|` on match arms a formatting issue?

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#119]
It is now possible in Rust to start a match arm with a `|`, e.g.,

```
match foo {
    | whatever => {}
}
```

Currently Rustfmt treats a leading `|` or not as significant code, i.e., preserves what the user chose to do. However, it is not semantically significant, so one might consider it a style issue, in which case Rustfmt should change it one way or the other (since we believe in consistent formatting, not preserving user input). As a counter-point, we do not strip unnecessary `()` although these also are not semantically significant.

So, there are three options:
* never use an initial `|`
* always use an intial `|`
* preserve the user choice.

**Comment by ubsan** [comment]
I personally want something like this: https://github.com/rust-lang-nursery/rustfmt/issues/2234

**Comment by chriskrycho** [comment]
👍 to @ubsan's suggestion. This is where Reason landed, for example.

**Comment by steveklabnik** [comment]
I really don't want leading `|`, so my preference is 1, then 3.

**Comment by jplatte** [comment]
> As a counter-point, we do not strip unnecessary `()` although these also are not semantically significant.

Unnecessary `()` are something you use in very few situations, if ever, though. Initial `|` on match arms seem to me like something you would either add everywhere, or nowhere. So I would consider it a style choice.

**Comment by nrc** [comment]
OK, it sounds like there is consensus that this is a formatting issue, but not on exactly what we should do.

IMO, using `|` instead of an indent is too radical a change at this stage, and is also inconsistent with the rest of our formatting choices because we heavily rely on indentation rather than punctuation to identify 'sub-items'.

Therefore I propose we accept option 1, that tools should remove leading `|`s. However, tools could support an option like https://github.com/rust-lang-nursery/rustfmt/issues/2234 (i.e., leading `|` without indentation).

**Comment by nrc** [comment]
Closed by #127
