### ISSUE TITLE
Macro uses

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#12]

**Comment by joshtriplett** [comment]
The statements proposal mentions the use of macros in statements.

We need to cover a few different cases here: macros with `()` as statements ("use them like a function call"), macros with `()` as expressions ("use them like a function call"), macros with `{}` as statements ("use them like a block"), and macros with `{}` as expressions ("don't").

**Comment by nrc** [comment]
The interesting (difficult) question is how to format the 'argument' to a macro, since these can be any sequence of tokens.

**Comment by joshtriplett** [comment]
@nrc True.  And that then raises the question of how opinionated we want to be on that.

I see two options: either we suggest style for what kinds of tokens you should use in a macro, or we don't and have to write a style that allows an arbitrary bag of tokens.

I'd lean towards the latter to avoid becoming too prescriptive about macros.  And we can argue that sufficiently popular and widespread macros *may* need special-cases in rustfmt.

**Comment by HadrienG2** [comment]
One such common case which could warrant dedicated handling is vec!. Because from a user's point of view, it does the same thing as an array constructor, it should be formatted identically.

**Comment by nrc** [comment]
In several other issues we've said that certain kinds of macro should follow their formatting. I want to note an exception here (and perhaps some more in the future):

when formatting a macro use, Rustfmt should not insert or remove trailing commas (or other punctuation) because these can be semantically significant in macros.

**Comment by joshtriplett** [comment]
@nrc Agreed, though we should also recommend in the style guidelines that function-like and initializer-like macros should accept trailing commas.

**Comment by nrc** [comment]
Closed by #110
