### ISSUE TITLE
Use visual indent for method chain with a small parent and single-line children

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/fmt-rfcs#125]
Currently we use block indent by default for every expressions and items (except use items).
I found this to be suboptimal with a method chain with a small parent and single-line children.
E.g. (the following example is taken from ﻿﻿https://github.com/rust-lang/rust/pull/49670):

```rust
// block indent
fmt.debug_struct("Foo")
    .field("bar", &self.bar)
    .field("baz", &self.baz)
    .field("addr", &format_args!("{}", self.addr))
    .finish()

// visual indent
fmt.debug_struct("Foo")
   .field("bar", &self.bar)
   .field("baz", &self.baz)
   .field("addr", &format_args!("{}", self.addr))
   .finish()
```

I would like to propose using visual indent for chains like this.

IIRC block indent was preferred to visual indent because it creates a right-ward drift and does't interact well with multi-line expressions like closures. These problems does not exist in a method chain like the one above.

**Comment by joshtriplett** [comment]
The same problem exists with such method chains: if you change `fmt` to something else, that cascades through the whole expression if you use visual indent, but only affects the first line if you use block indent.
