### ISSUE TITLE
Formatting the rust-lang/rust codebase

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/fmt-rfcs#133]
It seems clear that at some point we will want to programmatically format all of rust-lang/rust. I haven't found anything more than brief informal discussion of how to go about this, so I thought I would bring it up here. Please let me know if there is a better place to start this discussion or if the discussion has already happened somewhere.

Is it within scope for the style team or rustfmt team to make a proposal to the compiler team of how to make this happen, given all of your experience with rustfmt in all sorts of codebases, or is this something that you leave entirely up to the compiler team to sort out?

This is going to be a large enough effort with many stakeholders that it would be worthwhile putting together an RFC.

- How to land the formatting changes? A single huge commit, separate commits by crate, ...
- How to mitigate downsides? Every open PR and work in progress will hit merge conflicts; we will want clear guidance or even tooling to make the process smoother for PR authors. Any tooling we come up with could be helpful for adoption of rustfmt in other large Rust codebases too.
- Timeline. Do we not even want to think about this until after rustfmt stability has been settled and 1.0 has shipped? Or do we do it sooner to get more eyes on the rustfmt style and increase our confidence prior to 1.0?
<br>

<sub>Some relevant mentions:</sub>
 <sub>• [Formatting guidelines RFC](https://github.com/rust-lang/rfcs/pull/2436)</sub>
 <sub>• [Rustfmt stability RFC](https://github.com/rust-lang/rfcs/pull/2437)</sub>
 <sub>• [Rustfmt 1.0 tracking issue](https://github.com/rust-lang-nursery/rustfmt/issues/1860)</sub>
 <sub>• @topecongiro @nrc</sub>

**Comment by nrc** [comment]
I think this would mostly be up to the compiler team. I don't think we have much experience to bring to this other than 'don't try to run rustfmt on CI before it is stable'.

I've chatted a little bit to @nikomatsakis and iirc we thought one big commit with lots of advanced warning and a closed tree would be the way to do it.

**Comment by dtolnay** [comment]
Sounds good. If the compiler team owns this then I'll trust it is on their radar and will happen when it makes sense. With one big commit I assume they'll take care of the standard library as well so there is no action needed from the libs team for now. Thanks :)
