### ISSUE TITLE
static mut capitalisation

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#20]

**Comment by steveklabnik** [comment]
What is there to discuss here?

**Comment by ubsan** [comment]
@steveklabnik I personally think it should be `SNAKE_CAPS`, but some disagree, and the compiler doesn't say anything about it.

**Comment by steveklabnik** [comment]
Ah interesting, I also thought it was just `SNAKE_CAPS`.

**Comment by joshtriplett** [comment]
To me, ALL_CAPS strongly suggests a constant. I'd find it really surprising to see such an identifier modifiable.

**Comment by solson** [comment]
@joshtriplett I don't disagree, but a `static` can be mutable too, given `Mutex` or similar.

As far as I know, Rustfmt literally can't do naming of `static` based on whether it's mutable or not, so it might end up more consistent if we say ALL_CAPS means `static`/`static mut`/`const` and that's all.

Another option is using ALL_CAPS *only* for `const`. But in my experience, ALL_CAPS for all three is already a well-established convention.

**Comment by nrc** [comment]
I must admit, I haven't thought about this too much. One thought is that we don't distinguish local variables by mutability with caps or any other way, so maybe we shouldn't for globals too? Although I do agree with @joshtriplett that all caps does suggest a const.

**Comment by joshtriplett** [comment]
On October 8, 2016 2:10:48 AM PDT, Nick Cameron <notifications@github.com> wrote:
>I must admit, I haven't thought about this too much. One thought is
>that we don't distinguish local variables by mutability with caps or
>any other way, so maybe we shouldn't for globals too? Although I do
>agree with @joshtriplett that all caps does suggest a const.

While I wouldn't put this in a style guide, in the rare case where I had a static mut, I'd probably prefix it with `global_`.

**Comment by alexcrichton** [comment]
I personally feel that constants, statics, and static muts all fall in the same bucket of "global values" so they get the same naming conventions. I'd personally find it surprising if `static` had different naming conventions than `static mut`, especially because there are many `static` values that are indeed mutable! (e.g. `ATOMIC_USIZE_INIT`)

**Comment by nrc** [comment]
Another question: should Rustfmt enforce this? At the moment it does not change any names since this would require refactoring capabilities. It could warn if we wanted. If we used the rustc format for suggestions, these might be usable by a refactoring tool or IDE (although I suspect we'd need JSON output for that, which obvs is a big job). Alternatively, we could just mention it in the guide and not enforce in rustfmt.

I guess there is a bigger issue here of what Rustfmt should do about naming issues. Perhaps worth moving that discussion into a new thread.

**Comment by joshtriplett** [comment]
I don't think rustfmt should attempt automated refactoring or renaming. I do think that if we recommend a style, either rustfmt or rustcb should at least detect the issue.

**Comment by joshtriplett** [comment]
See https://github.com/rust-lang/rust/pull/37162 ; the compiler now gripes if you don't capitalize these.

**Comment by nrc** [comment]
Given that this is now enforced by lint, I propose that this issue be closed since there is nothing for us to do.

FCP with intention to close.

**Comment by joshtriplett** [comment]
Reluctantly agreed, though I'd also comment that I wish the style team had been included in that discussion.  I'd also suggest that we contact the compiler team and ask them to CC the style team on future issues like that.

**Comment by brson** [comment]
Close sgtm.

**Comment by nrc** [comment]
Discussed at the style team meeting. Closing.
