### ISSUE TITLE
Generics declarations

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#29]
In functions, structs, enums, traits, impls, etc.

**Comment by nrc** [comment]
It would be great is someone wanted to sketch this one out!

**Comment by joshtriplett** [comment]
# Generics

By convention, prefer to use single uppercase letters as names of generics.  Together with the rules below, this makes it exceedingly rare to ever need to break generics across multiple lines.

Never put a space before or after the `<`, or before the `>`. Only put a space after the `>` if a space would appear there anyway in the absence of the generics.  (For instance, `fn func<T>(...` but `struct SomeType<T> {`.)

Never put a space before a `,`. always put a space after a `,`.

Prefer to put the generics on one line, if they fit:

```rust
fn func1<T, U>(x: Vec<T>, y: Vec<U>) {
    ...
}

fn func2<T: Display, U: Debug>(x: Vec<T>, y: Vec<U>) {
    ...
}
```

If the generics don't fit on one line, prefer to use a where clause to reduce the size of the generics:

```rust
fn func3<T, U>(x: Vec<T>, y: Vec<U>)
    where T: Debug, U: Display
{
    ...
}
```

If the generics still don't fit, or you don't want to use a where clause, prefer to split another part of the line (such as function parameters) to make enough room:

```rust
fn func4<T, U>(
    x: Vec<T>,
    y: Vec<U>,
) {
    ...
}

fn func5<T, U>(
    x: Vec<T>,
    y: Vec<U>,
) where T: Display, U: Debug
{
    ...
}

fn func6<T: Display, U: Debug>(
    x: Vec<T>,
    y: Vec<U>,
)
{
    ...
}
```

If the generics still don't fit, even after using a where clause and splitting another part of the line, then split the generics across multiple lines. In this case:
- Put a newline after the `<`.
- Place each clause on a line by itself.
  - Block-indent each clause one level beyond the item that has the generics attached.
  - Put a trailing comma on each clause.
- Put the `>` on the line after the last item, indented to the same level as the item with the generics attached.

These cases should almost never come up with single-character generic names.

```rust
fn ridiculously_long_name_1<
    T,
    U,
>(
    x: Vec<T>,
    y: Vec<U>,
) where T: Display, U: Debug
{
    ...
}

// Not preferred; use a where clause instead
fn ridiculously_long_name_2<
    T: Display,
    U: Debug,
>(
    x: Vec<T>,
    y: Vec<U>,
)
{
    ...
}
```

For structs:

```rust
struct SomeStruct<T, U> {
    x: Vec<T>,
    y: Vec<U>,
}

struct SomeStruct<T: Display, U: Debug> {
    x: Vec<T>,
    y: Vec<U>,
}

struct SomeStruct<T, U>
    where T: Display, U: Debug
{
    x: Vec<T>,
    y: Vec<U>,
}
```

(WIP)

**Comment by joshtriplett** [comment]
OK, first draft in https://github.com/rust-lang-nursery/fmt-rfcs/issues/29#issuecomment-271501101 .

Doesn't yet cover every case of breaking in the middle of generic parameters.  Those cases need completing, starting with "tuple structs".

**Comment by nrc** [comment]
+1 to basically all of that, thanks for spec'ing it up. A few nits and a question:

> By convention, prefer to use single uppercase letters as names of generics.

I hesitate to get into naming conventions, I kinda think they are beyond our purview. I know sometimes, some people like having longer names for generics (esp since it is conventional for assoc types).

> and always put a space after a comma (,)

unless there is a newline

> If the generics don't fit on one line, consider using a where clause to reduce the size of the generics

are we happy to let Rustfmt do this? (Presumably this would be optional, but default to on)

I'm assuming that the examples starting from "For structs or unions:" are informative rather than normative?

**Comment by nrc** [comment]
This looks pretty straightforward given that it mostly aligns with principles we've previously discussed. It's been around for a short while too. So, I think it is ready for FCP.

**Comment by joshtriplett** [comment]
@nrc 
Regarding naming conventions: I only said "prefer to", not "must".  I think documenting widespread existing convention makes sense, in an advisory, non-mandatory way.

I added a note about newlines after commas.

I would rather not have rustfmt convert between generics and where clauses; I can think of scenarios where I'd select one or the other depending on factors other than length.  I'd rather rustfmt preserve the choice of where or non-where, and just format that.

I intended all the examples as normative with respect to generics, and with respect to resolved fmt-rfcs unless I missed a detail.  Each of those cases has some slightly different concerns than functions (for instance, structs/unions have the generic parameters appear right before the opening brace).

**Comment by nrc** [comment]
> I only said "prefer to", not "must".

This still seems too strong. Perhaps I am splitting hairs with the semantics here, but "prefer to" suggests something that might be enforced by a linter, but I think that is not something I would want a linter to ever suggest.

> I think documenting widespread existing convention makes sense, in an advisory, non-mandatory way.

I agree, but don't think that the style guide is the right place to do it. We could very easily feature-creep into opining on all sorts of Rust coding and I think it is best if we limit ourselves to formatting, as much as possible.

> Each of those cases has some slightly different concerns than functions

could you point these out explicitly please?

**Comment by joshtriplett** [comment]
@nrc
> could you point these out explicitly please?

structs, unions, enums, and traits have the generic parameters appear right before the opening brace; the examples show to include a space between the `>` and the opening brace, and to put `> {` on the same line if breaking within the generics.

Tuple structs have a parenthesis instead of a brace, and the examples show to write `>(` without a space, and to put it on the same line if breaking within the generics.

Trait impls and impl-fors have one or two (respectively) additional places to break the line before breaking within the generics.

**Comment by nrc** [comment]
We've changed our process: rather than requiring a full RFC, a PR to close this issue only requires making the changes discussed here to the [style guide](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md). You can see more details about the process in the [readme for this repo](https://github.com/rust-lang-nursery/fmt-rfcs#the-formatting-rfc-process).

If you'd like to help with this work, let me know, I'd be very happy to help you help us.
