### ISSUE TITLE
type aliases

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#32]
Again, I'd like to discuss generics separately (#29), so that should make this one pretty trivial.

**Comment by ubsan** [comment]
```rust
type X /* <- one line */ = Foo;
type LongName = /* <- don't break here */
  FooBar; /* <- pull this down */
```

**Comment by nrc** [comment]
Pretty simple one, I think, ready for FCP.

**Comment by nrc** [comment]
Questions:

If there is a where clause, should we leave on one line, e.g.,

```
type Foo<T> where T: Foo = Bar;
```

I propose not, since that is what we agreed for where clauses in general.

In which case how should we break this?

```
type Foo<T>
where
    T: Foo,
= Bar;
```

Would be my suggestion, the only downside is that we had previously decided to break *after* the `=` for the non-where case if we need to break the line. Perhaps we should revisit that?

And to check - trailing comma here is OK?

**Comment by joshtriplett** [comment]
@nrc Type aliases with where clauses seem like a sufficiently different case to be worth evaluating separately from functions with where clauses.  And they have kind of an awful order of terms, which we can't do anything about.

I think I'd argue that in the majority of cases type aliases should inline the constraints inside the `<>`, to improve readability.  In the case of a where clause, though, I'd agree with your proposed formatting.  The standard response to someone going "ewww" in reaction can be to suggest not using a where clause in a type alias. :)

I don't think we should change the decision to break after the `=` in the non-where case.
