### ISSUE TITLE
#[macro_use]

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang-nursery/fmt-rfcs#36]
How should a `#[macro_use]` declaration work with `extern crate`?  This may fall under more general "attributes" formatting, but it seems like a distinct case that may merit different formatting.

I've seen two popular styles:

``` rust
#[macro_use] extern crate example;

#[macro_use]
extern crate example;
```

**Comment by solson** [comment]
The same-line style works well for not breaking up sorted blocks:

```rust
extern crate a;
extern crate b;
#[macro_use] extern crate c;
extern crate d;
```

Two-line style breaks the flow somewhat:

```rust
extern crate a;
extern crate b;
#[macro_use]
extern crate c;
extern crate d;
```

And from what I've seen, most people would suggest a blank line before, like:


```rust
extern crate a;
extern crate b;

#[macro_use]
extern crate c;
extern crate d;
```

And sometimes even:


```rust
extern crate a;
extern crate b;

#[macro_use]
extern crate c;

extern crate d;
```

So... I kind of prefer the same-line style. I'll admit that it has an ugliness of its own, though. I think we're choosing from the lesser of two evils here.

On the plus side, the macro module system RFC(s) will make `#[macro_use]` go away entirely, as I understand it, so we don't need to worry too much about this one. (cc @nrc to confirm/deny)

**Comment by joshtriplett** [comment]
It seems a bit unfortunate that we can't write `extern crate example #[macro_use];`, in that order.  But yes, if RFCs end up making `#[macro_use]` obsolete, we can drop the formatting guidelines for it at that time.

**Comment by ubsan** [comment]
I haven't personally ever had a case like @scott is talking about; that said, I would rather `#[macro_use]` attributes be like all other attributes, i.e., on a line on it's own.

**Comment by joshtriplett** [comment]
@ubsan I tend to agree, though I can also see the appeal of putting it on one line, and I wouldn't complain if the conclusion went the other way.

**Comment by solson** [comment]
We'll need to decide how having attributes affects the surrounding formatting regardless, as in my latter 3 code samples. This comes up for `mod`, too.

I agree with the separate lines argument for consistency.

**Comment by joshtriplett** [comment]
@solson Personally, I don't think this needs surrounding blank lines.  I'd prefer to keep all `extern crate` lines together in one sorted block, even if they have `#[macro_use]` attributes.

**Comment by keeperofdakeys** [comment]
It's worth noting that macros will (hopefully) start using the normal `use` statement soon, which should make `#[macro_use]` much rarer.

**Comment by nrc** [comment]
I prefer to treat macro_use just like any other attribute, I don't really see any reason why it should be treated differently. And yes, eventually, it should just go away.

**Comment by nrc** [comment]
FCP with inclination to close (that is, treat macro_use like any other attribute).

**Comment by solson** [comment]
Even if we're treating it like any other attribute (which is probably the right idea), that's actually not specific enough. Which of the last three examples in https://github.com/rust-lang-nursery/fmt-rfcs/issues/36#issuecomment-257124179 do you mean?

**Comment by solson** [comment]
There are also other options, like pulling it out of the sorted block entirely:

```rust
extern crate a;
extern crate b;
extern crate d;

#[macro_use]
extern crate c;
```

**Comment by solson** [comment]
I should also note that this also affects `mod` with `#[path = "..."]`. The tension is essentially caused by having an item in a sorted list (of `mod`s or `extern crates`) that has some extra stuff compared to the other items.

**Comment by nrc** [comment]
I think option 2 matches what is in the style guide (https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md#attributes). I think that treating it like every other attribute means that it does not afffect ordering or grouping (like wise with `#[path]`).
