### ISSUE TITLE
Whitespace for negative integers

### ISSUE THREAD

**Issue by johnthagen** [rust-lang-nursery/fmt-rfcs#45]
The style guide currently says `Use spaces around binary operators`, but what about when `-` is used as a negation "operator"?

Should it be:
```rust
fn main() {
    let x = -1;

    let name = match x {
        -1 => "negative one",
        _ => "other",
    };
}

```
Or:
```rust
fn main() {
    let x = - 1;

    let name = match x {
        - 1 => "negative one",
        _ => "other",
    };
}

```

Sorry if this is trivially obvious, but I couldn't find it explicitly listed. `intellij-rust` currently formats the match arm to `- 1` like in the bottom example, but I didn't want to report a bug unless I could verify that the first example is indeed what the Rust style guide is preferring.

**Comment by regexident** [comment]
For the sake of making it easier to "vote":

```
-1 (no space)
```

**Comment by regexident** [comment]
```
- 1 (space)
```

**Comment by joshtriplett** [comment]
@regexident
> Sorry if this is trivially obvious, but I couldn't find it explicitly listed.

The style guide currently says "Do not include a space between a unary op and its operand".  That applies to the negation operator, too.

I don't think we should change that.

**Comment by johnthagen** [comment]
@joshtriplett Thanks for the info, I had missed that. I think the problem was more a problem of finding the most up-to-date style guide.  If you Google "rust style guide":

- First hit https://aturon.github.io/ (old)
- Second hit https://github.com/rust-lang/rust-guidelines (old)
  - This has a link to a rendered: https://doc.rust-lang.org/1.12.0/style/README.html (also old)
  - Third link: https://github.com/rust-lang-nursery/fmt-rfcs (new, but not the actual style guide)
    - If you know to navigate to `guide/guide.md` then you find the most up-to-date style guide

Now that I've found the current authoritative style guide, I think this issue can be closed, but maybe we could link the `guide/guide.md` from this repos `README` to make it a little easier to navigate to. I'll open PRs on the other old projects to try to get people directed to this repo a little easier.

**Comment by joshtriplett** [comment]
@johnthagen Good idea. Just submitted #46 for that.

**Comment by nrc** [comment]
Seems clear to me that unary minus is a unary operator and therefore should have to space. I'll leave this open (and FCPed) in case anyone objects, but I expect to close this soon (I believe the style guide does not need further amendment).

**Comment by joshtriplett** [comment]
Agreed.  I wanted to make sure nothing made this unclear in the style guide, but it sounds like the problem in this case arose from "which style guide?".

**Comment by johnthagen** [comment]
@nrc @joshtriplett  Agreed this can be closed. Thanks all!

For reference I also opened the following:

- https://github.com/aturon/aturon.github.io/issues/6
- https://github.com/rust-lang/rust-guidelines/pull/55
