### ISSUE TITLE
Whitespace in associated type syntax

### ISSUE THREAD

**Issue by jgouly** [rust-lang-nursery/fmt-rfcs#51]
The associated type syntax:

    trait Example {
          type Item;
    }
    
    fn example<T: Example<Item=u32>>() {}

Is currently formatted to:

    trait Example {
          type Item;
    }
    
    fn example<T: Example<Item = u32>>() {}

I've mostly seen people use the version with no spaces (and rust/src/lib* has more occurences of "<Item=", than "<Item =".. but not by much).

Just opening this issue to make sure that it's taken into account, when deciding on a default style.

**Comment by joshtriplett** [comment]
Interesting issue!  On the one hand, I find the syntax without spaces preferable when using a simple type like `u32`.  On the other hand, the spaces might help when using a non-trivial type that includes generic parameters itself.

**Comment by nrc** [comment]
We used spaces in Rustfmt for pretty much @joshtriplett 's reason - complex types. It's kind of an interesting trade-off though, I definitely prefer no spaces at first blush. However, I think to a large extent it is just getting used to the more spaced version.

**Comment by ubsan** [comment]
I prefer spaces, personally; in all my binops, there are spaces.

**Comment by nrc** [comment]
Anyone else have input here? I'm putting in to FCP, expecting to go with spaces around `=`.

**Comment by joshtriplett** [comment]
@nrc How would you feel about the rule "use no spaces for a single-identifier type name (such as `T` or `SomeType`); use spaces for any other type"?

**Comment by nrc** [comment]
@joshtriplett that's an unusual rule, I don't think we change the formatting of operators depending on the shape of the operands elsewhere. I fear this will look inconsistent, although it is has a certain appealing logic.

**Comment by bugaevc** [comment]
I'm used to following the [PEP 8 recommendation](https://www.python.org/dev/peps/pep-0008/#other-recommendations) of always putting spaces around =, unless it indicates a named argument or a default value (that is what this PR is about). I guess other Python people are used to this too.

**Comment by joshtriplett** [comment]
@nrc Unusual, yes, but I think it'd match what people tend to do in practice.

**Comment by devonhollowood** [comment]
I think the spaces definitely improve readability here, and for what it's worth I have never really liked the "no spaces around `=` before named arguments / default values" rule from `PEP8`. I think it gets too cramped if the RHS is more complex than just a single identifier.

**Comment by samlh** [comment]
Servo's tidy script avoids taking a stance here[1], and so do I :). I'm vaguely in favor of spaces everywhere, I suppose, if a choice is needed.

[1] https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py#L510

**Comment by jimmycuadra** [comment]
Another 👍 for spaces from me.

**Comment by joshtriplett** [comment]
Based on discussion in today's style meeting, I'm withdrawing the suggestion to format simple cases without spaces, in favor of the consensus of always using a space.

**Comment by nrc** [comment]
We've changed our process: rather than requiring a full RFC, a PR to close this issue only requires making the changes discussed here to the [style guide](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md). You can see more details about the process in the [readme for this repo](https://github.com/rust-lang-nursery/fmt-rfcs#the-formatting-rfc-process).

If you'd like to help with this work, let me know, I'd be very happy to help you help us.
