### ISSUE TITLE
We need convention about functions inside of a function

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang-nursery/fmt-rfcs#58]
We need strong convention where to place a nested function.
```rust
fn foo() {
    fn bar() {}

    bar();
}

fn foo() {
    bar();

    fn bar() {}
}
```

**Comment by regexident** [comment]
I'm not sure I'd want rustfmt to force a particular function placement upon my code. I usually declare inline functions close to the point of usage, but not necessarily at the very top of the scope. Just like I'd declare a variable close to its actual use, not at the very top of the scope, as it was common in old-timey C.

**Comment by KalitaAlexey** [comment]
@regexident,
At first, it is not about rustfmt at all.
It is about convention.
At second, rustfmt can have optional parameter instead of forced placement.

**Comment by nrc** [comment]
I think this changes from function to function - sometimes one or the other is clearer, sometimes it is clearer to have the function in the middle of code somewhere.

I think this is not really a formatting issue and thus beyond the remit of the format RFC process.
