### ISSUE TITLE
Determine where to maintain the Rust Style Guide

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang-nursery/fmt-rfcs#6]
We need to maintain a document similar to the old Rust Style Guide (recently removed from the rust repository).  Where should that document live?  (In its own repository?  In the rustfmt repository to allow patches to it and rustfmt simultaneously?)  How should we maintain it?  Where should we host a rendered copy of it?

**Comment by nrc** [comment]
There was some discussion of this in mandate RFC and in the PR discussion. But we should discuss this further to make sure we're all on board.

**Comment by nrc** [comment]
I think we are all agreed on this and the style guide is in the repo.
