### ISSUE TITLE
other control flow expressions (for, if, if let, while, while let, loop)

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#62]

**Comment by nrc** [comment]
Note that this is easy because we do not expect anything to be controversial, it is likely to be quite a large volume of work.

**Comment by ubsan** [comment]
Basically, we've agreed that it should look something like

```rust
if foo {
}
```

in the simple case; in more complex cases, the space between `if` and `foo` should be treated as any other newline-place. For example,

```rust
if foo
    && bar
{
}
```
should be used, as opposed to

```rust
if
    foo
    && bar
{
}
```

or any other variation. The rest follows from the rest of the style guide.

For `X let` style things, where there's an `=`, and for `for` loops, where there's an `in`, the `in` and `=` should go on the next line, like other binops:

```rust
for x
    in y
{
}


if let Some(x)
    = opt
{
}
```

**Comment by joshtriplett** [comment]
@ubsan Complete and total agreement here.

**Comment by topecongiro** [comment]
If the last line of condition only consists of closing parens and alike, I prefer to combine it with the opening bracket of the body block.

For example, do these:
```rust
// 1
if !self.config.file_lines().intersects(
    &self.codemap.lookup_line_range(
        stmt.span,
    ),
) {
    return;
}

// 2
if arg_str.lines().last().map_or(false, |last_line| {
    last_line.contains("//")
}) {
    foo();
}

// 3
if let Some(trait_ref_str) =
    rewrite_trait_ref(
        context,
        &trait_ref,
        offset,
        &generics_str,
        true,
        polarity_str,
        result_len,
    ) {
    foo();
} else {
    bar();
}
```
instead of:
```rust
// 1
if !self.config.file_lines().intersects(
    &self.codemap.lookup_line_range(
        stmt.span,
    ),
)
{
    return;
}

// 2
if arg_str.lines().last().map_or(false, |last_line| {
    last_line.contains("//")
})
{
    foo();
}

// 3
if let Some(trait_ref_str) =
    rewrite_trait_ref(
        context,
        &trait_ref,
        offset,
        &generics_str,
        true,
        polarity_str,
        result_len,
    )
{
    foo();
} else {
    bar();
}
```

**Comment by joshtriplett** [comment]
@topecongiro Interesting! I don't often run into conditionals that complex, but for all of the examples you mention, I agree with the idea of combining the closing parens with the opening brace.

**Comment by nrc** [comment]
I agree on cases 1 and 2, but not on case 3, because in that case there is no difference in indentation to indicate the start of the block.

**Comment by joshtriplett** [comment]
@nrc I agree; I tend to double-indent the continuation line of the conditional in that case, to more clearly distinguish it.
