### ISSUE TITLE
array literals and repeated array initialisers

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#63]
`[a, b, c]` and `[expr; expr]`, e.g., `[a; 42]`. We might want to consider `vec![]` as a special case macro too.

**Comment by VictorGavrish** [comment]
I ran into a problem with `rustfmt` regarding two-dimensional arrays like `[[u8; 4]; 4]`. I think the most ergonomic way to format these arrays is something like this:

```rust
[
    [2, 2, 4, 4],
    [0, 2, 2, 0],
    [0, 2, 2, 2],
    [2, 0, 0, 2],
]
```

`rustfmt` insists on formatting it like this:

```rust
[[2, 2, 4, 4], [0, 2, 2, 0], [0, 2, 2, 2], [2, 0, 0, 2]]
```

This is better in some cases, but much worse when you are actually thinking of a square matrix or some 2d projection.

I think `rustfmt` should preserve line breaks in such cases. Let the programmer decide which looks better.

**Comment by solson** [comment]
I was looking at the nalgebra docs today and I realized rustfmt will run into trouble with matrices there, too.

E.g. [here](http://nalgebra.org/vectors_and_matrices/#matrix-construction):

```rust
let m = Matrix3x4::new(11, 12, 13, 14,
                       21, 22, 23, 24,
                       31, 32, 33, 34);
```

**Comment by nrc** [comment]
In general these kind of things (semantic line breaks) are difficult (perhaps impossible) for Rustfmt to get right. I think the best approach is not to try and rely on the user to add `rustfmt_skip` attributes.

**Comment by VictorGavrish** [comment]
I feel like relying on `rustfmt_skip` is a bad idea if `rustfmt` aims to be ubiquitous, or else it will not become ubiquitous and the benefit of the tool's existence diminishes.

There will be projects where, for example, two-dimensional are too widespread to sprinkle `rustfmt_skip` everywhere, so the project would opt not to use `rustfmt` at all. And if you're breaking one formatting rule, why not then break a dozen more? Also if you're working on this project, you might not be familiar with the established formatting at all, and thus break these rules without even knowing about them.

I think it would be a good idea for `rustfmt` to try to respect user formatting some more, as long as it is within some general guidelines. For example, format

```rust
[
[2, 2, 4, 4],
[0, 2, 2, 0],
[0, 2, 2, 2],
[2, 0, 0, 2],
]
```

as

```rust
[
    [2, 2, 4, 4],
    [0, 2, 2, 0],
    [0, 2, 2, 2],
    [2, 0, 0, 2],
]
```

enforcing increasing indentation for nested objects, and format

```rust
[[2, 2, 4, 4],[0, 2, 2, 0],[0, 2, 2, 2],[2, 0, 0, 2]]
```

as

```rust
[[2, 2, 4, 4], [0, 2, 2, 0], [0, 2, 2, 2], [2, 0, 0, 2]]
```

enforcing spaces after commas, but not butcher the general layout of the thing.

Likewise,

```rust
let m = Matrix3x4::new(11, 12, 13, 14,
    21, 22, 23, 24,
    31, 32, 33, 34);
```

should be formatted as either

```rust
let m = Matrix3x4::new(11, 12, 13, 14,
                                      21, 22, 23, 24,
                                      31, 32, 33, 34);
```

or

```rust
let m = Matrix3x4::new(
    11, 12, 13, 14,
    21, 22, 23, 24,
    31, 32, 33, 34,
);
```

or something elese, but still respect user-defined line breaks.

**Comment by HadrienG2** [comment]
In the Matrix3x4 use case, I think that part of the issue is that this constructor's interface is not so well-designed to begin with. The code would be both harder to get wrong and easier to format it the interface took three tuples instead.

```rust
let m = Matrix3x4::new((11, 12, 13, 14),
                       (21, 22, 23, 24),
                       (31, 32, 33, 34));
```

**Comment by solson** [comment]
@HadrienG2 I agree. I think it's fair for us to say either use syntax that more accurately reflects the semantics (your array example) or use the `rustfmt_skip` attribute.

**Comment by joshtriplett** [comment]
@HadrienG2 Or perhaps three tuples.  But yes, I agree completely.  In almost every case where I've thought it might make sense to group arguments or similar with more than one per line, it almost always seemed preferable to group the arguments semantically, with a tuple or a data type.  If you have a dozen arguments, and they make the most sense to think about in groups of 3 or 4, use (and define if necessary) those semantic groups.

**Comment by nrc** [comment]
> I think it would be a good idea for rustfmt to try to respect user formatting some more, as long as it is within some general guidelines. For example, ...

Rustfmt originally tried to work like this. It was an absolute nightmare. The implementation details and edge cases that occurred were basically impossible to reconcile. You end up with formatting that never reaches a fixed point or that is non-deterministic in extreme cases. We quickly moved to ignoring most user formatting and has time goes by we've been ignoring more and more.

**Comment by nrc** [comment]
I propose that:

* for the `[expr, *]` form (and for `vec![expr,*]`) we follow the rules for function calls.
* for `[expr; expr]` and (`vec![expr; expr]`) we prefer breaking after the `;` rather than in either expression, and in that case we put the two `expr`s on separate, block-indented lines, e.g.,

```
let a = [
    a_very_long_expression();
    1 + 1 + 1 + 1
];
```

(Note there is no trailing semi-colon, but that is due to Rust syntax requirements).

I expect having to break the `[expr; expr]` form to be rare, and rustfmt should prefer to break other, surrounding expressions if possible.

**Comment by solson** [comment]
Should we apply array-like formatting to all `macro![...]` or just `vec![...]`?

**Comment by nrc** [comment]
Hmm, good question. I think all `[]` macros (or at least all those whose arguments can be parsed as `expr,*` or `expr; expr`).

**Comment by gbutler69** [comment]
Yikes! For this:

> @HadrienG2 I agree. I think it's fair for us to say either use syntax that more accurately reflects the semantics (your array example) or use the rustfmt_skip attribute

You suggest changing the API to this:

````rust
let m = Matrix3x4::new([11, 12, 13, 14],
                       [21, 22, 23, 24],
                       [31, 32, 33, 34]);
````

From this:

````rust
let m = Matrix3x4::new(11, 12, 13, 14,
                       21, 22, 23, 24,
                       31, 32, 33, 34);
````

So that the formatting rules don't need to respect user imposed new-lines? What if the underlying API requires the latter form for efficiency? It seems a little short-sighted to impose that API's should accommodate formatting rather than the other way around.

**Comment by joshtriplett** [comment]
@gbutler69 No, the proposal is that if you want to write the latter rather than the former, you might need to add `#[rustfmt_skip]`.
