### ISSUE TITLE
struct and tuple literals

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#64]

**Comment by nrc** [comment]
## structs

**Single line version**:  `Path { field1, field2 }`. Note spaces before and after `{`, before `}`, no trailing comma

**Mutli-line version**:

```
Path {
    field1,
    field2,
}
```

Note space before `{`, block indent, trailing comma.

Use the mutli-line version if the literal does not fit in the line, if the fields are not short (see #47), or if any of the field sub-expressions cover multliple lines. Otherwise use the single-line version.

**Comment by nrc** [comment]
## tuple variants

Unit variants are trivial.

Struct variants should follow the guidelines for structs.

Tuple variants should follow the guidelines for function calls.

**Comment by nrc** [comment]
## Functional record update

Does not get a trailing comma, is otherwise treated like any other field. There is no space after the `..`. E.g.,

```
Path {
    field1,
    field2,
    ..some_expr
}
```

**Comment by Luthaf** [comment]
> Single line version: Path { field1, field2 }. Note spaces before and after {, before }, no trailing comma

I kinda dislike this, up to the point that it was my major friction point with rustfmt. I don't know how others feels about this, but I am commenting here so that this is taken in consideration =). I would be happy with this not being the default but being configurable.

To me, this have way to many spaces. I would prefer `Path{field1, field2}`, without the spaces. The only rationalisation I can get for this is that inline struct literals feels like constructors in C++, with the braces playing the role of parenthesis.

A version with a space before the left brace looks OK to me too: `Path {field1, field2}`, and it would look more like the multiline version.

**Comment by chriskrycho** [comment]
@Luthaf for a counterpoint, the most immediate predecessor for this is JavaScript's object types. It's common there to write the same kind of short structure that way there:

```js
const field1 = 'whatever';
const field2 = 42;
const path = { field1, field2 };
```

I'd also note that this feels quite different from construction in C++ *to me* – and I want to be made more actively aware that there *isn't* any function call happening! – but that's just me. I think the specified default is a good default, but I certainly wouldn't be *hostile* to its being configurable either.

**Comment by joshtriplett** [comment]
On May 16, 2017 1:47:57 AM PDT, Luthaf <notifications@github.com> wrote:
>> Single line version: Path { field1, field2 }. Note spaces before and
>after {, before }, no trailing comma
>
>I kinda dislike this, up to the point that it was my major friction
>point with rustfmt. I don't know how others feels about this, but I am
>commenting here so that this is taken in consideration =). I would be
>happy with this not being the default but being configurable.
>
>To me, this have way to many spaces. I would prefer `Path{field1,
>field2}`, without the spaces. The only rationalisation I can get for
>this is that inline struct literals feels like constructors in C++,
>with the braces playing the role of parenthesis.
>
>A version with a space before the left brace looks OK to me too: `Path
>{field1, field2}`, and it would look more like the multiline version.

I find it jarring to see anything right next to a curly brace like this. And struct constructors have obvious analogues in other languages, using similar syntax.
