### ISSUE TITLE
Vec::new() versus vec![]

### ISSUE THREAD

**Issue by clarcharr** [rust-lang-nursery/fmt-rfcs#70]
This is a discussion that was discussed in Manishearth/rust-clippy#1542; it would be nice to have a consensus on whether `vec![]` should ever be an expression used by itself, or if `Vec::new()` is preferred.

I've seen `Vec::new()` in a majority of places, but some people seem to prefer `vec![]`.

**Comment by nrc** [comment]
I don't really consider this a formatting issue, so is a bit out of scope for this process. Personally I use `vec![]` because it is shorter and consistent with initialising a non-empty array, and I see no reason not to use it.
