### ISSUE TITLE
Wrapping strategies for function calls

### ISSUE THREAD

**Issue by vitiral** [rust-lang-nursery/fmt-rfcs#73]
I would like to define the formatting strategy for function calls. It does not currently exist in the [style guide][1]

[1]: https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md

# Basic idea
**Method 1**:
```
very_long_module_name::this_is_a_really_long_function(arg1,
                                                      arg2,
                                                      arg3,
                                                      "this is a raw s\
                                                       tring and is ter\
                                                       ible")
```
should instead be **Method 2**:
```
very_long_module_name::this_is_a_really_long_function(
    arg1, arg2, arg3, 
    "this is a raw string and is terible")
```

rustfmt currently uses the **Method 1** way too often. I'm not sure the right balance here. Like @joshtriplett said in #47   , you really want to define "simple". IMO "simple" would be:

- If the function and all args fit within the line length, just do that.
- Otherwise use **Method 1** if **Method 1** only takes up two lines
- Otherwise use **Method 2**:
  - arguments always start on their own indented line
  - arguments are listed normally as long as they don't go over the line length limit
  - any argument that would go over the line length limit goes on it's own line
  - anything over 25 characters goes on it's own line

**Comment by nrc** [comment]
Dup of #65
