### ISSUE TITLE
Specify rules for breaking long `where` conditions.

### ISSUE THREAD

**Issue by ticki** [rust-lang-nursery/fmt-rfcs#75]
https://users.rust-lang.org/t/new-style-guidelines/10037/41?u=ticki

**Comment by joshtriplett** [comment]
@ticki I prefer option 3 you proposed, except that I would put operators at the start of the following line to make the continuation lines more obviously continuations of the previous line:

```
where
    Abcdef: Aaaaaaaaaaa + Bbbbbbbbbbbbbb + Cccccccccccccc
        + Ddddddddddddddd + Eeeeeeeeeeeee + Ffffffffffffffffff
        + Ggggggggggggg + Hhhhhhhhhhh + Iiiiiiiiii + Jjjjjjjjj,
```

**Comment by clarcharr** [comment]
I'd personally love to see a consensus on this.

An example from [len-trait](https://docs.charr.xyz/len-trait/len_trait/index/trait.IndexRanges.html):

Original:
```
impl<T: ?Sized, Idx> IndexRanges<Idx> for T
where
    T: Index<Range<Idx>, Output = Self::Output> + Index<RangeTo<Idx>, Output = Self::Output> + Index<RangeFrom<Idx>, Output = Self::Output> + Index<RangeInclusive<Idx>, Output = Self::Output> + Index<RangeToInclusive<Idx>, Output = Self::Output> + Index<RangeFull>, 
```

Option 1:
```
impl<T: ?Sized, Idx> IndexRanges<Idx> for T
where
    T: Index<Range<Idx>, Output = Self::Output>,
    T: Index<RangeTo<Idx>, Output = Self::Output>,
    T: Index<RangeFrom<Idx>, Output = Self::Output>,
    T: Index<RangeInclusive<Idx>, Output = Self::Output>,
    T: Index<RangeToInclusive<Idx>, Output = Self::Output> + Index<RangeFull>,
```

Option 2:
```
impl<T: ?Sized, Idx> IndexRanges<Idx> for T
where
    T: Index<Range<Idx>, Output = Self::Output>
       + Index<RangeTo<Idx>, Output = Self::Output>
       + Index<RangeFrom<Idx>, Output = Self::Output>
       + Index<RangeInclusive<Idx>, Output = Self::Output>
       + Index<RangeToInclusive<Idx>, Output = Self::Output> + Index<RangeFull>
```

Option 3:
```
impl<T: ?Sized, Idx> IndexRanges<Idx> for T
where
    T: Index<Range<Idx>, Output = Self::Output>
        + Index<RangeTo<Idx>, Output = Self::Output>
        + Index<RangeFrom<Idx>, Output = Self::Output>
        + Index<RangeInclusive<Idx>, Output = Self::Output>
        + Index<RangeToInclusive<Idx>, Output = Self::Output> + Index<RangeFull>
```

Another option:
```
impl<T: ?Sized, Idx> IndexRanges<Idx> for T
where
    T:
        Index<Range<Idx>, Output = Self::Output>
        + Index<RangeTo<Idx>, Output = Self::Output>
        + Index<RangeFrom<Idx>, Output = Self::Output>
        + Index<RangeInclusive<Idx>, Output = Self::Output>
        + Index<RangeToInclusive<Idx>, Output = Self::Output> + Index<RangeFull>
```

**Comment by clarcharr** [comment]
Also, this should apply to `trait` bounds as well:

```
pub trait IndexRanges<Idx>: Index<Range<Idx>, Output = Self::Output> + Index<RangeTo<Idx>, Output = Self::Output> + Index<RangeFrom<Idx>, Output = Self::Output> + Index<RangeInclusive<Idx>, Output = Self::Output> + Index<RangeToInclusive<Idx>, Output = Self::Output> + Index<RangeFull> { }
```

**Comment by joshtriplett** [comment]
@clarcharr I prefer either option 3 or option 1.  I didn't actually realize you could write option 1 (multiple separate bounds for the same type).  I like option 1 better, but I don't know if rustfmt should convert to that if the user didn't write it that way in the first place.

**Comment by joshtriplett** [comment]
General feeling from the rust style team: rustfmt should not rewrite T: A+B+C to T: A, T: B, T: C , though perhaps clippy might provide it as a style lint for long bounds.

**Comment by nrc** [comment]
I think, we are agreed on option 3 from the above list, in terms of indentation and `+` to start the line. I agree with @clarcharr that this should also apply to trait bounds.

A question: should we force one bound per line (as in https://github.com/rust-lang-nursery/fmt-rfcs/issues/75#issuecomment-294046086 and similar to function arguments) or should we allow filling up the lines (as in the original OP on users.r-l.o and as with addition expressions). I guess this depends on whether we expect bounds to be simple or complex in general. I don't have too much of an intuition for that.

cc @withoutboats, since they seem to have more trait bounds than most in their life

**Comment by joshtriplett** [comment]
Consensus from today's style meeting: always break each component of the bound onto its own line, starting each line with a `+`:

```rust
where
    T: Something<very long>
        + Sync
        + Send
        + Display
        + Debug
        + Copy
```

If you want this to stay on one line, you could do this:

```rust
where
    T: Something<very long>,
    T: Sync + Send + Display + Debug + Copy
```

**Comment by tomprince** [comment]
Was there any consideration given to grouping some of the traits? In particular, I'd like to suggest grouping any of `Sync`, `Send` and lifetime bounds that occur together on their own line.

**Comment by nrc** [comment]
@tomprince this seems like it is overstepping the mark for 'smartness' in rustfmt. If you want to group traits in this way you should use the suggestion in the above comment

**Comment by joshtriplett** [comment]
In particular, I think we're pretty uncomfortable with the idea of having rustfmt change the order of code or add/remove tokens, as opposed to changing things like whitespace.

**Comment by ticki** [comment]
@tomprince not really relevant for this issue.
