### ISSUE TITLE
Allow the return type to be on next line.

### ISSUE THREAD

**Issue by ticki** [rust-lang-nursery/fmt-rfcs#77]
In some cases, I find expanding the argument like

```rust
    pub fn alloc(
        &self,
        buf: disk::SectorBuf,
        description: &'static str,
    ) -> impl Future<page::Pointer, Error> {
```

excessive, so I prefer something like

```rust
    pub fn alloc(&self, buf: disk::SectorBuf, description: &'static str)
    -> impl Future<page::Pointer, Error> {
```

which is illegal per new proposal, if I understand it correctly.

**Comment by nrc** [comment]
My opinion is that when a function signature gets long enough that it must be split across multiple lines, even if that can be done by just splitting off the return type, then it is nearly always complex enough that it reads better on multiple lines (that is, one line per arg). In the given example, I do prefer the first version.

I think we discussed something very similar when discussing the function guidelines which is whether to allow formatting such as:
```
pub fn alloc(
    &self, buf: disk::SectorBuf, description: &'static str
)
```

We decided 'no' there and I think the same reasoning applies here.

I'm entering FCP to close. There hasn't been explicit support and I think it is covered by the reasoning from a previous discussion. Happy to un-FCP if there is a discussion to be had here.

**Comment by ticki** [comment]
> We decided 'no' there and I think the same reasoning applies here.

I don't see how it applies here?

**Comment by nrc** [comment]
> I don't see how it applies here?

The reasoning is that when a function is long enough to be split to multiple lines, we should do so for the sake of 'reading complexity', not try to do the minimal line breaking possible

**Comment by internetionals** [comment]
> The reasoning is that when a function is long enough to be split to multiple lines, we should do so for the sake of 'reading complexity', not try to do the minimal line breaking possible

The problem with 'reading complexity' is that as often as not the complexity is for a large part in the return part of the definition, but that this complexity doesn't extend to the argument list.

Some possibly illustrative examples:

From futures:
>      fn poll(&mut self) -> Poll<Option<Self::Item>, Self::Error> {

From nom:
>      pub fn tag_cl<'a,'b>(rec:&'a[u8]) -> Box<Fn(&'b[u8]) -> IResult<&'b[u8], &'b[u8]> + 'a> {

In the method department do I often see function declarations where the return specification is close to half the length of the declaration. The argument list is only self with sometimes one additional parameter. And when lifetimes are involved this often gets worse.

Though I have to concede that some of the code that ran into line breaking, might involve names that are rather long and might benefit from a cleaner module structure.

**Comment by nrc** [comment]
@internetionals I think you are right in that the complexity of args vs return type might be unrelated. However, it is generally pretty hard to get Rustfmt to reason about complexity vs line length. I think the only practical way to address this would be to have a length heuristic for the return type, if it is exceeded, then we put the return type on its own line. However, I think this is pretty much an edge case that this would happen where the whole line does not exceed the max width. So, I'd be open to incorporating such a heuristic, but I don't think it is important enough that we need to include it in the style guide or implement it *right now*.

**Comment by internetionals** [comment]
@nrc I think that standpoint is reasonable and just wanted to point out that there are some valid cases worth considering, but I wholeheartedly agree that there are more important things right now to consider. And return signature complexity might (or might not, too soon to tell) change a lot once 'impl Trait' lands.
