### ISSUE TITLE
trait bounds

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang-nursery/fmt-rfcs#80]
i.e. one single bound, whether on a type parameter, trait, associated type, etc.

Ordinarily, bounds don't get out of hand enough for the length of one particular bound to be an issue. However, when writing specialized trait aliases, piling all the bounds into one spot can accrue some line-length issues. Here's an example from the `len_trait` crate:

```rust
pub trait IndexRanges: Index<Range<usize>, Output=Self> + Index<RangeTo<usize>, Output=Self> + Index<RangeFrom<usize>, Output=Self> + Index<RangeFull, Output=Self> { }
```

Prior iterations of the `multistr` crate instead had these bounds, and others, on an associated type.

**Comment by joshtriplett** [comment]
Interesting!  My inclination would be to wrap that like this:

```rust
pub trait IndexRanges:
    Index<Range<usize>, Output=Self>
    + Index<RangeTo<usize>, Output=Self>
    + Index<RangeFrom<usize>, Output=Self>
    + Index<RangeFull, Output=Self>
{
    ...
}
```

**Comment by harpocrates** [comment]
In the interest of being consistent with comma delimited lists, we could have the following

```rust
pub trait IndexRanges:
    Index<Range<usize>, Output=Self> +
    Index<RangeTo<usize>, Output=Self> +
    Index<RangeFrom<usize>, Output=Self> +
    Index<RangeFull, Output=Self> +
{
    ...
}
```

The first bound being misaligned with the rest bothers me a bit. Another solution could be

```rust
pub trait IndexRanges
    : Index<Range<usize>, Output=Self>
    + Index<RangeTo<usize>, Output=Self>
    + Index<RangeFrom<usize>, Output=Self>
    + Index<RangeFull, Output=Self>
{
    ...
}
```

although that breaks the convention of having no space on the left side of the colon.

**Comment by QuietMisdreavus** [comment]
Yeah, that first one @harpocrates wrote out is my reflex, just to have the identifiers on the same column. It's unfortunate about not having the + on the last line, though.

**Comment by harpocrates** [comment]
@QuietMisdreavus I'm confused about the second part of your comment - both of my examples will parse and both have a + on the last line. Glad you agree though!

**Comment by QuietMisdreavus** [comment]
Oh, I didn't realize it allowed a trailing + on the bounds like that. If that's the case, then I support that form even more!

**Comment by joshtriplett** [comment]
General feeling from the rust style team: rustfmt should not rewrite `T: A+B+C` to `T: A, T: B, T: C` , though perhaps clippy might provide it as a style lint for long bounds.

**Comment by clarcharr** [comment]
Oh, hey, my crate!

Right now I format it like this:

```
pub trait IndexRangesMut<Idx>: IndexMut<Range<Idx>>
                             + IndexMut<RangeTo<Idx>>
                             + IndexMut<RangeFrom<Idx>>
                             + IndexMut<RangeInclusive<Idx>>
                             + IndexMut<RangeToInclusive<Idx>>
                             + IndexMut<RangeFull>
                             + IndexRanges<Idx>
```

Which looks most similar to @harpocrates' second option. I see that sort of style a lot in Haskell, for example like this:

```
lst =
    [ "string 1"
    , "string 2"
    ]
```

**Comment by nrc** [comment]
cc #75, which covers much of the same ground

**Comment by clarcharr** [comment]
I should add that I've started formatting like:

```
pub trait Trait:
    Bound +
    OtherBound +
```

which works nice.

**Comment by joshtriplett** [comment]
@clarcharr The style from your first comment uses visual indents, which we've avoided in the default style.  The style in your second comment uses block indent, but personally I'm really not a fan of putting the operator at the end of each line.  See https://github.com/rust-lang-nursery/fmt-rfcs/issues/18#issuecomment-301622527 for detailed rationale on that.

**Comment by harpocrates** [comment]
@joshtriplett @clarcharr I'm not sure that the operator-at-the-end-of-the-line (which I agree with) is something that applies here. The `+` in trait bounds is a separator more like the `,` between arguments/tuples/generics/etc than like `||` between expressions.

Even the rust parser handles `+` in trait bounds as a separator (the same way it parses `,` in arguments/tuples/generics/etc and not like other actual operators).

**Comment by joshtriplett** [comment]
@harpocrates It still feels odd and inconsistent, to me, to put the `+` at the end of the line, rather than the start of the next.  I understand how the Rust parser handles it, but it still *looks* like an operator, and it *acts* like "addition" of traits.
