### ISSUE TITLE
Spaces around `=` in attributes

### ISSUE THREAD

**Issue by s3rvac** [rust-lang-nursery/fmt-rfcs#82]
Should we put spaces around the equal sign (`=`) in attributes? For example, should we write
```rust
#![recursion_limit="1024"]
```
or
```rust
#![recursion_limit = "1024"]
```
?

Notes:
* [rustfmt](https://github.com/rust-lang-nursery/rustfmt) does not seem to care about this. It keeps whatever amount of whitespace I use. However, when I write `let x=1;`, it corrects that to `let x = 1;`.
* The Rust Reference [uses both styles](https://doc.rust-lang.org/reference.html#attributes), even inside of a single code block:
```rust
#![crate_type = "lib"]

// ...

#[cfg(target_os="linux")]
```
* There is no example code for this in the [examples](https://github.com/rust-lang-nursery/fmt-rfcs/tree/master/example) part of this repo.
* I was unable to find this piece of information in the [Attributes section](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md#attributes) of the guide. Does the following rule also apply to attributes?

> Do include spaces around binary ops (i.e., x + 1, not x+1) (including =).

If so, then maybe we should add this to the Attributes section of the guide (including an example) to prevent confusion and add a formatting rule to `rustfmt`.

**Comment by nrc** [comment]
I agree we do need to decide this. I tend to write it without spaces myself, however, given that everywhere else `=` is used, it gets spaces I think we probably ought to do that here too.

**Comment by Boscop** [comment]
I also think there should be spaces. I used to write it without spaces (because I read it that way in example code) but now I always write the spaces for consistency.

**Comment by ivandardi** [comment]
I like it without spaces. Python does it with function default arguments, and I'm really glad they do, otherwise function declarations would be really long. Likewise, if we opt for no spaces around `=` in attributes, we can compress the code a little bit more, and I really wouldn't like having to split an attribute over multiple lines.
