### ISSUE TITLE
Fields with reserved names

### ISSUE THREAD

**Issue by dbrgn** [rust-lang-nursery/fmt-rfcs#84]
If I do serialization of the JSON object `{"type": "foo", "count": 3}`, the struct would have to look like that to match the field names:

```rust
struct Obj {
    type: String,
    count: u32,
}
```

The thing is that `type` is a reserved keyword, so it can't be used.

Of course I can use the Serde rename feature. But is there a convention on how to call the field instead, e.g. trailing slash (`type_`), leading slash (`_type`) or modification (`typ` or `tipe`)?

**Comment by joshtriplett** [comment]
Leading underscore has a specific meaning in Rust, namely that it suppresses warnings about something going unused. So, I'd suggest trailing underscore.

**Comment by nrc** [comment]
Personally I prefer a trailing underscore. The convention in the compiler (which faces this issue a lot) is to modify the keyword (`typ`, `krate` are widely used).

We've shied away from naming conventions here, we prefer to concentrate on purely formatting issues. This does seem like a reasonable thing to cover in the naming section of the style guide though.

**Comment by gbutler69** [comment]
C# allows you to use, `@reserved` instead of `reserved` if you want to use a reserved word as an identifier. Isn't $ a valid character for identifiers in rust? How about `$reserved` or `$$reserved` for code generated identifiers that would otherwise use reserved words?

**Comment by nrc** [comment]
> Isn't $ a valid character for identifiers in rust?

I don't think it is - `$` is used to identify macro variables.

**Comment by mqudsi** [comment]
Just to point out that a trailing underscore is also autocomplete-friendly for users expecting to find a function/member with a name that coincides with a reserved keyword.
