### ISSUE TITLE
Formatting especially long argument lists with short arguments

### ISSUE THREAD

**Issue by Alex-Addy** [rust-lang-nursery/fmt-rfcs#87]
rustfmt would like to format the following:
```
let _ = vec![
            9, 0, 0, 0,
            9, 1, 0, 1,
            9, 2, 1, 0,
            9, 3, 1, 1,
            9, 4, 3, 5,
            9, 7, 0, 1,
            0
        ];
```
like
```
let _ = vec![9,
            0,
            0,
            0,
            9,
            1,
            0,
            1,
            ...
        ];
```
This is not very helpful normally, but in my case those groupings have a particular meaning, so I turned off formatting on the item. Looking at it more I feel like there could be a better default for such a code block. Perhaps preferring to list multiple arguments for each line up to a character limit before going to the next line. Or maybe even detecting an edge case like this and not modifying the code therein.

**Comment by gsingh93** [comment]
I think this is something you would use `#[rustfmt_skip]` for.

**Comment by Alex-Addy** [comment]
`#[rustfmt_skip]` requires rust nightly which I am not using. But `#[cfg_attr(rustfmt, rustfmt_skip)]` works which is what I did. It just isn't ideal to have to do formatting manually for long argument lists, and sprinkling pragmas all over the place is less than ideal.

**Comment by joshtriplett** [comment]
I don't want to suggest that the right answer is to change/restructure your code, but one of the reasons we'd originally ignored cases like this was that we hoped such code could look like:

```rust
let _ = vec![
            (9, 0, 0, 0),
            (9, 1, 0, 1),
            (9, 2, 1, 0),
            (9, 3, 1, 1),
            (9, 4, 3, 5),
            (9, 7, 0, 1),
        ];
```

But at the same time, I can understand that you might need to interface with some API that doesn't work that way.

It'd be nice if there was a semantically insignificant grouping mechanism you could use for that, as a hint that certain sets go together. You *might* consider making a macro for that, which allows you to provide sets of what look like 4-tuples, and automatically translate them and add the trailing `0`. rustfmt would then format it accordingly, and it'd be more readable.

But at the same time, it *might* be worth considering a rustfmt attribute like `#[rustfmt(group(4))]`

**Comment by Alex-Addy** [comment]
For my particular case it is just a coincidence that they look like 4-tuples. The 9 is a command that takes three arguments, there are a number of other commands that take a different number of arguments. And those arguments can be derived from different values. So my code looks like:

```rust
let _ = vec![
        add, reg_min+0, 0, 0,
        add, reg_min+0, 1, 1,
        eq, reg_min+1, reg_min+0, 3,
        jt, reg_min+1, 3424,
        noop,
        out, 69,
        halt,
]
```
I had simplified it to keep some distracting details from getting involved, but it appears that I simplified it too much. It is looking like this might just be too weird to deal with.

**Comment by Alex-Addy** [comment]
That is to say, I am not seeking some perfect formatting rule. Just better handling of long argument lists.

**Comment by solson** [comment]
Ooh, thanks for that code example. I have similar code in an emulator project with vectors of variable-length machine code bytes that I format as one instruction per line, and I hadn't considered how rustfmt would format it before.

In cases like that, where the number of elements per line is very semantic and human-chosen, I think it's fair to require a "rustfmt skip" attribute. We should make it more concise than `#[cfg_attr(rustfmt, rustfmt_skip)]`, though.

**Comment by joshtriplett** [comment]
Sure, I've done the same thing, writing machine code in an array.

**Comment by Alex-Addy** [comment]
So it seems that the consensus is to use cfg_attr. Which is fine for such specific structuring. It is sort of annoying that the smallest unit I can place that attr on is a function and not the declaration causing me problems.

**Comment by solson** [comment]
@Alex-Addy When [this feature](https://github.com/rust-lang/rust/issues/15701) is stabilized, attributes will be able to apply to single statements.

**Comment by solson** [comment]
Oh, in fact, the statements part is already stabilized, because this successfully compiles: https://play.rust-lang.org/?gist=80c1aa6ff33a3aa9a9bc7c895d495f93&version=stable

However, rustfmt ignores the `rustfmt_skip` on a statement. We should open an issue for that.

**Comment by solson** [comment]
Opened https://github.com/rust-lang-nursery/rustfmt/issues/1810.

**Comment by Alex-Addy** [comment]
About when could I expect that on a version of rustfmt? Alternatively, how do I install a version that has that issue closed?

**Comment by nrc** [comment]
@Alex-Addy it should be in rustfmt-nightly already (if you are not using the nightly rustfmt, uninstall the non-nightly version, `cargo install rustfmt-nightly`, if you are using nightly already you can update by using `install --force`

**Comment by Alex-Addy** [comment]
It looks like I can't compile that with the stable compiler. I get this error:
```
error[E0554]: #[feature] may not be used on the stable release channel
  --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.1/src/lib.rs:11:1
   |
11 | #![feature(rustc_private)]
```
I'm closing this issue as it is pretty much resolved to my satisfaction. I'll be watching for statements to hit stable.
