### ISSUE TITLE
Extend `wrap_match_arms` config to have an idea of "block-like" expression

### ISSUE THREAD

**Issue by CAD97** [rust-lang-nursery/fmt-rfcs#88]
For example,

```rust
match cond {
    _ => unsafe {
        // do something unsafe
    },
}
```

## The actual change

Add a third option to the config `wrap_match_arms` (optionally as the default, though that should probably go through a separate RFC), `non-block-like` (pending bikeshedding). When `wrap_match_arms = non-block-like`, the formatter will behave like `wrap_match_arms = true` for non-block-like expressions and `wrap_match_arms = false` for block-like expressions.

## Block-like expressions

A "non-block-like expression" is any expression that is not a block-like expression. A "block-like expression" is an expression that has a singular, trailing block.

Block-like expressions:

```rust
unsafe {
    // code
}

match val {
    // code
}

if condition {
    // code
}

vec! [
    // items
]
```

Non-block-like expressions:

```rust
foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo()

if condition {
    // code
} else {
    // code
}
```

So a block-like is any expression which has one block of code contained within matched brackets as the tail end of the expression.

**Comment by nrc** [comment]
I think that what you are proposing is already what we plan to have as the default and only option for match arms.

**Comment by CAD97** [comment]
Didn't see anything about it when I looked, but I'll be honest I didn't look very hard.

If this is planned anyway feel free to close this.
